version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "4001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: insurance
    volumes:
      - insurance_data:/var/lib/postgresql/data

volumes:
  insurance_data: