// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.1
// source: pkg/gRPC/insurance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewInsurance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderAddr string `protobuf:"bytes,1,opt,name=senderAddr,proto3" json:"senderAddr,omitempty"`
	Amount     int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	CarImage   []byte `protobuf:"bytes,3,opt,name=carImage,proto3" json:"carImage,omitempty"`
}

func (x *NewInsurance) Reset() {
	*x = NewInsurance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gRPC_insurance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewInsurance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewInsurance) ProtoMessage() {}

func (x *NewInsurance) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gRPC_insurance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewInsurance.ProtoReflect.Descriptor instead.
func (*NewInsurance) Descriptor() ([]byte, []int) {
	return file_pkg_gRPC_insurance_proto_rawDescGZIP(), []int{0}
}

func (x *NewInsurance) GetSenderAddr() string {
	if x != nil {
		return x.SenderAddr
	}
	return ""
}

func (x *NewInsurance) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NewInsurance) GetCarImage() []byte {
	if x != nil {
		return x.CarImage
	}
	return nil
}

type NewPayoff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverAddr string `protobuf:"bytes,1,opt,name=receiverAddr,proto3" json:"receiverAddr,omitempty"`
	CarImage     []byte `protobuf:"bytes,2,opt,name=carImage,proto3" json:"carImage,omitempty"`
}

func (x *NewPayoff) Reset() {
	*x = NewPayoff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gRPC_insurance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPayoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPayoff) ProtoMessage() {}

func (x *NewPayoff) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gRPC_insurance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPayoff.ProtoReflect.Descriptor instead.
func (*NewPayoff) Descriptor() ([]byte, []int) {
	return file_pkg_gRPC_insurance_proto_rawDescGZIP(), []int{1}
}

func (x *NewPayoff) GetReceiverAddr() string {
	if x != nil {
		return x.ReceiverAddr
	}
	return ""
}

func (x *NewPayoff) GetCarImage() []byte {
	if x != nil {
		return x.CarImage
	}
	return nil
}

var File_pkg_gRPC_insurance_proto protoreflect.FileDescriptor

var file_pkg_gRPC_insurance_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x69, 0x6e, 0x73, 0x75, 0x72,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x49, 0x6e,
	0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x63, 0x61, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x4b, 0x0a, 0x09, 0x4e,
	0x65, 0x77, 0x50, 0x61, 0x79, 0x6f, 0x66, 0x66, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x63, 0x61, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x32, 0x73, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x75,
	0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0d, 0x2e, 0x4e, 0x65, 0x77, 0x49, 0x6e,
	0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x2c, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x6f, 0x66, 0x66, 0x12, 0x0a, 0x2e, 0x4e, 0x65, 0x77, 0x50,
	0x61, 0x79, 0x6f, 0x66, 0x66, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x3b, 0x5a,
	0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x73, 0x65,
	0x72, 0x6f, 0x76, 0x2f, 0x63, 0x61, 0x72, 0x5f, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63,
	0x65, 0x2f, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x67, 0x52, 0x50, 0x43, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_gRPC_insurance_proto_rawDescOnce sync.Once
	file_pkg_gRPC_insurance_proto_rawDescData = file_pkg_gRPC_insurance_proto_rawDesc
)

func file_pkg_gRPC_insurance_proto_rawDescGZIP() []byte {
	file_pkg_gRPC_insurance_proto_rawDescOnce.Do(func() {
		file_pkg_gRPC_insurance_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gRPC_insurance_proto_rawDescData)
	})
	return file_pkg_gRPC_insurance_proto_rawDescData
}

var file_pkg_gRPC_insurance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_gRPC_insurance_proto_goTypes = []interface{}{
	(*NewInsurance)(nil),  // 0: NewInsurance
	(*NewPayoff)(nil),     // 1: NewPayoff
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_pkg_gRPC_insurance_proto_depIdxs = []int32{
	0, // 0: Insurance.CreateInsurance:input_type -> NewInsurance
	1, // 1: Insurance.Payoff:input_type -> NewPayoff
	2, // 2: Insurance.CreateInsurance:output_type -> google.protobuf.Empty
	2, // 3: Insurance.Payoff:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_gRPC_insurance_proto_init() }
func file_pkg_gRPC_insurance_proto_init() {
	if File_pkg_gRPC_insurance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gRPC_insurance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewInsurance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gRPC_insurance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPayoff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gRPC_insurance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gRPC_insurance_proto_goTypes,
		DependencyIndexes: file_pkg_gRPC_insurance_proto_depIdxs,
		MessageInfos:      file_pkg_gRPC_insurance_proto_msgTypes,
	}.Build()
	File_pkg_gRPC_insurance_proto = out.File
	file_pkg_gRPC_insurance_proto_rawDesc = nil
	file_pkg_gRPC_insurance_proto_goTypes = nil
	file_pkg_gRPC_insurance_proto_depIdxs = nil
}
