version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: contract_outbox
    environment:
      - REDIS_USER=admin
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data